#!/bin/sh

set -e 

if [ "$1" = "configure" ]
then
	if ! getent group quantum > /dev/null 2>&1
	then
		addgroup --system quantum >/dev/null
	fi
	if ! getent passwd glance > /dev/null 2>&1
	then
		adduser --system --home /var/lib/quantume --ingroup glance --no-create-home --shell /bin/false quantum
	fi
	chown -R quantum:quantum /var/lib/quantum/ /var/log/quantum/ /etc/quantum/
	chmod 0700 /etc/glance/ /var/log/glance/
fi

#DEBHELPER#
