#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
	if ! getent passwd quantum > /dev/null 2>&1
	then
		adduser --system --home /usr/share/quantum --ingroup quantum --no-create-home --shell /bin/bash quantum
	fi

	if ! getent group quantum > /dev/null 2>&1
	then
		addgroup --system quantum >/dev/null
	fi

	chown quantum:quantum -R /var/log/quantum /var/run/quantum /etc/quantum
	chmod 0700 /etc/quantum
	chmod 0700 /var/log/quantum
fi

#DEBHELPER#
